version: "2.0"

services:

  postgres:
    container_name: identitybase-postgres
    restart: unless-stopped
    image: postgres:9.6.9-alpine
    #ports:
    #  - 5432:5432
    #  - 5433:5433
    networks:
      - default
    environment:
      - POSTGRES_DB=identitybase
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev

  # Reverse proxy
  nginx:
    container_name: identitybase-nginx
    restart: unless-stopped
    image: openresty/openresty:alpine
    ports:
      - 80:80
    #  - 443:443
    networks:
      default:
        aliases:
          - identitybase.local
          - auth.identitybase.local
          - api.identitybase.local
    volumes:
      - ./nginx/config:/usr/local/openresty/nginx/conf

  identitybase:
    container_name: identitybase-authority
    restart: unless-stopped
    image: identitybasenet/identitybase:latest
    build: ../../.
    #ports:
    #  - 5000:5000
    networks:
      - default
    volumes:
      - ./identitybase/config:/usr/local/identitybase/config
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  # RP1 website (dotnet core)
  # http://aspnetcoreweb:21402
  aspnetcoreweb:
    container_name: identitybase-web
    restart: unless-stopped
    image: identitybasenet/aspnetcoreweb:latest
    build: ../AspNetCoreWeb/.
    #ports:
    #  - 5002:5002
    networks:
      - default
    environment:
      - APP__AUTHORITY=http://auth.identitybase.local
      - APP__API1BASEADDRESS=http://aspnetcoreapi:5001
      - ASPNETCORE_ENVIRONMENT=Development

  # Web service (dotnet core)
  aspnetcoreapi:
    container_name: identitybase-api1
    restart: unless-stopped
    image: identitybasenet/aspnetcoreapi:latest
    build: ../AspNetCoreApi/.
    #ports:
    #  - 5001:5001
    networks:
      - default
    environment:
      - APP__AUTHORITY=http://auth.identitybase.local
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  default:
